# -*- mode: ruby -*-
# vi: set ft=ruby :

#######################################################################################################
#
# Requires vagrant-triggers plugin
#
# $ vagrant plugin install vagrant-triggers
#
#######################################################################################################

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "rafacas/fedora19-plain"
  config.vm.box = "boxcutter/debian82"
  config.vm.synced_folder "../..", "/libvirt-go"

  config.vm.provision "shell", privileged: true, inline: <<-EOF

    /vagrant/debian82_bootstrap.sh

    /vagrant/go_install.sh

  EOF

  config.trigger.after :provision do
      run "vagrant reload"
  end

end
